import Head from "next/head";
import { auth, provider } from "./firebase";
import { signInWithPopup } from "firebase/auth";
import * as React from "react";

export default function Home() {
  const [user, setUser] = React.useState(null);
  const handleSignIn = () => {
    signInWithPopup(auth, provider)
      .then((result) => {
        console.log(result.user);
        setUser(result.user);
        localStorage.setItem("kryptonite-pm-user", JSON.stringify(result.user));
      })
      .catch((error) => {
        console.log(error.message);
      });
  };

  React.useEffect(() => {
    const json = localStorage.getItem("kryptonite-pm-user");
    if (!json) return;
    const savedUser = JSON.parse(json);
    if (savedUser) {
      setUser(savedUser);
    }
  }, []);

  return (
    <>
      <Head>
        <title>Kryptonite - Encrypted Password Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="relative flex min-h-full flex-col items-center overflow-hidden font-heading gap-8">
          <div className="absolute inset-0 bg-[url(../assets/images/grid.svg)] bg-center [mask-image:linear-gradient(180deg,white,rgba(255,255,255,0))]"></div>
          <div className="pt-8 text-5xl">Kryptonite</div>
          <div className="text-xl tracking-widest font-sans">
            An encrypted password manager
          </div>
          {user ? <div>Logged in</div> : <LoginButton onClick={handleSignIn} />}
        </div>
      </main>
    </>
  );
}

function LoginButton({ onClick }) {
  return (
    <button
      onClick={onClick}
      className="font-heading text-white text-center text-lg bg-black p-6 px-20 w-full max-w-xl tracking-wider rounded-xl shadow hover:-translate-y-2 transform duration-200 ease-in"
    >
      Sign-in with Google
    </button>
  );
}
